Repository postmarketOS/pmbootstrap, pull requests merged in 2018-02, with the labels that each got.

#1213 Fix screwed up progress bars in Travis output
  pmb/build/_package.py
  pmb/chroot/init.py
  test/check_checksums.py
  test/test_build_package.py
Labels: fix, infrastructure

#1215 Update unicsy-demo
  aports/main/unicsy-demo/APKBUILD
Labels: packaging, update

#1211 main: add triggerhappy
  aports/main/triggerhappy/APKBUILD
  aports/main/triggerhappy/triggerhappy.openrc
Labels: packaging

#1205 Automatically generate a calibration matrix for libinput
  aports/device/device-asus-tf101/APKBUILD
  aports/device/device-leeco-s2/APKBUILD
  aports/device/device-lg-h815/APKBUILD
  aports/device/device-motorola-potter/APKBUILD
  aports/device/device-motorola-shamu/APKBUILD
  aports/device/device-samsung-espresso10/APKBUILD
  aports/device/device-samsung-i9070/APKBUILD
  aports/device/device-samsung-i9195/APKBUILD
  aports/device/device-samsung-maguro/APKBUILD
  aports/device/device-samsung-manta/APKBUILD
  aports/device/device-samsung-s6500d/APKBUILD
  aports/device/device-semc-anzu/APKBUILD
  aports/device/device-teclast-x80pro/APKBUILD
  aports/device/device-xiaomi-ido/APKBUILD
  aports/main/devicepkg-dev/APKBUILD
  aports/main/devicepkg-dev/devicepkg_build.sh
Labels: enhancement, packaging

#1193 mkbootimg: replace python version with c version.
  aports/main/mkbootimg/APKBUILD
  aports/main/unpackbootimg/APKBUILD
  pmb/parse/bootimg.py
Labels: packaging

#1219 New device: Samsung Galaxy Note 8.0 (WiFi) n5110
  aports/device/device-samsung-n5110/90-device-samsung-n5110.rules
  aports/device/device-samsung-n5110/APKBUILD
  aports/device/device-samsung-n5110/Kona_WM1811/Kona_WM1811.conf
  aports/device/device-samsung-n5110/Kona_WM1811/hifi.conf
  aports/device/device-samsung-n5110/Kona_WM1811/lp.conf
  aports/device/device-samsung-n5110/asound.state
  aports/device/device-samsung-n5110/deviceinfo
  aports/device/device-samsung-n5110/pointercal
  aports/device/linux-samsung-n5110/APKBUILD
  aports/device/linux-samsung-n5110/compiler-gcc6.h
  aports/device/linux-samsung-n5110/config-samsung-n5110.armhf
Labels: device

#1228 Various linux packages: Fix broken dev subpackage
  aports/device/linux-teclast-x80pro/APKBUILD
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: fix, packaging

#1234 Package kernel-scripts separately to fix cross-compiled linux-*-dev packages
  aports/main/kernel-scripts/APKBUILD
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: fix, packaging

#1233 Check kernel config options based on the architecture
  pmb/config/__init__.py
  pmb/parse/kconfig.py
Labels: enhancement, pmbootstrap

#1236 Add a check for binfmt_misc
  pmb/chroot/binfmt.py
  pmb/helpers/other.py
Labels: enhancement, usability

#1232 Rudimentary ZSH autocompletion helper
  helpers/pmbootstrap-autocompletion.zsh
Labels: enhancement, usability

#1226 [WIP] gp-peak display
  aports/device/device-gp-peak/APKBUILD
  aports/device/device-gp-peak/deviceinfo
  aports/device/linux-gp-peak/APKBUILD
  aports/device/linux-gp-peak/linux-gp-peak.start
  aports/main/postmarketos-base/APKBUILD
  aports/main/postmarketos-base/postmarketos-base.post-install
Labels: device, enhancement

#1231 Wireguard for postmarketos-stable
  aports/main/linux-postmarketos-stable/APKBUILD
  aports/main/linux-postmarketos-stable/config-postmarketos-stable.aarch64
  aports/main/linux-postmarketos-stable/config-postmarketos-stable.armhf
  aports/main/linux-postmarketos-stable/config-postmarketos-stable.x86_64
  aports/main/wireguard-postmarketos-stable/APKBUILD
Labels: kernel, packaging

#1210 pmbootstrap build --src: override source for any package
  aports/main/linux-postmarketos-mainline/APKBUILD
  pmb/build/_package.py
  pmb/helpers/frontend.py
  pmb/helpers/mount.py
  pmb/parse/arguments.py
  test/test_build_package.py
  test/test_frontend.py
  test/testdata/build_local_src/APKBUILD
Labels: enhancement, pmbootstrap

#1225 postmarketos-ui-i3wm
  aports/device/device-nokia-n900/APKBUILD
  aports/device/device-nokia-n900/i3wm/i3status.conf
  aports/device/device-nokia-n900/i3wm/i3wm.conf
  aports/main/postmarketos-ui-i3wm/APKBUILD
  aports/main/postmarketos-ui-i3wm/lock.sh
  aports/main/postmarketos-ui-i3wm/postmarketos-ui-i3wm.post-install
Labels: dont_merge_pr, enhancement

#1202 Index parser: support multiple package providers
  pmb/aportgen/busybox_static.py
  pmb/aportgen/musl.py
  pmb/build/_package.py
  pmb/build/other.py
  pmb/chroot/apk.py
  pmb/chroot/apk_static.py
  pmb/chroot/initfs_hooks.py
  pmb/helpers/frontend.py
  pmb/helpers/pkgrel_bump.py
  pmb/parse/apkindex.py
  pmb/parse/arguments.py
  pmb/parse/depends.py
  test/test_apk_static.py
  test/test_build_is_necessary.py
  test/test_keys.py
  test/test_parse_apkindex.py
  test/test_parse_depends.py
  test/test_upstream_compatibility.py
  test/testdata/apkindex/key_missing
  test/testdata/apkindex/key_twice
  test/testdata/apkindex/new_line_missing
  test/testdata/apkindex/no_error
Labels: fix, pmbootstrap

#1222 New device: Nexus 5X (LG Bullhead)
  aports/device/device-lg-bullhead/APKBUILD
  aports/device/device-lg-bullhead/deviceinfo
  aports/device/linux-lg-bullhead/APKBUILD
  aports/device/linux-lg-bullhead/compiler-gcc6.h
  aports/device/linux-lg-bullhead/config-lg-bullhead.aarch64
  aports/device/linux-lg-bullhead/driver-fix.patch
  aports/device/linux-lg-bullhead/static-inline.patch
  aports/device/linux-lg-bullhead/undefined-screen_info.patch
Labels: device

#1240 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/0002-tools-objtool-Makefile-don-t-assume-sync-check.sh-is.patch
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1244 gp-peak: Set deviceinfo_flash_fastboot_max_size
  aports/device/device-gp-peak/APKBUILD
  aports/device/device-gp-peak/deviceinfo
Labels: device, enhancement

#1243 gp-peak: Add support for osk-sdl and audio
  aports/device/device-gp-peak/APKBUILD
  aports/device/device-gp-peak/device-gp-peak.start
  aports/device/device-gp-peak/fb.modes
  aports/device/linux-gp-peak/APKBUILD
  aports/device/linux-gp-peak/linux-gp-peak.start
  aports/main/postmarketos-base/APKBUILD
  aports/main/postmarketos-base/postmarketos-base.post-install
Labels: device, enhancement

#1250 APKINDEX not found message: Only show in verbose log
  pmb/parse/apkindex.py
Labels: fix, infrastructure, pmbootstrap

#1251 New device: infocus-flatfish
  aports/device/device-infocus-flatfish/APKBUILD
  aports/device/device-infocus-flatfish/deviceinfo
  aports/device/linux-infocus-flatfish/01_timeconst_fix.patch
  aports/device/linux-infocus-flatfish/02_fix_paranoid_network_disabled.patch
  aports/device/linux-infocus-flatfish/03_fix_pm_build.patch
  aports/device/linux-infocus-flatfish/APKBUILD
  aports/device/linux-infocus-flatfish/compiler-gcc6.h
  aports/device/linux-infocus-flatfish/config-infocus-flatfish.armhf
Labels: device

#1252 Patch amazon-thor's kernel to properly set the RGB mode
  aports/device/linux-amazon-thor/06_fix_mdss_fb_rgb_mode.patch
  aports/device/linux-amazon-thor/APKBUILD
  aports/device/linux-amazon-thor/config-amazon-thor.armhf
Labels: device, fix

#1253 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1245 New device (Jolla Phone)
  aports/device/device-jolla-sbj/APKBUILD
  aports/device/device-jolla-sbj/deviceinfo
  aports/device/linux-jolla-sbj/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-jolla-sbj/APKBUILD
  aports/device/linux-jolla-sbj/compiler-gcc6.h
  aports/device/linux-jolla-sbj/config-jolla-sbj.armhf
  aports/device/linux-jolla-sbj/duplicate-return-address-definition.patch
Labels: device, packaging

#1260 samsung-i9195: fix kernel config (USB network working)
  aports/device/linux-samsung-i9195/APKBUILD
  aports/device/linux-samsung-i9195/config-samsung-i9195.armhf
Labels: device, fix

#1259 Fix menuconfig arch check
  pmb/build/menuconfig.py
Labels: fix, pmbootstrap

#1256 qemu: allow the user to specify the kernel flavor
  pmb/parse/arguments.py
  pmb/qemu/run.py
Labels: qemu

#1247 Don't mark all packages as explicitly installed
  pmb/chroot/apk.py
Labels: fix, pmbootstrap

#1264 New device: Moto G 4G (2013)
  aports/device/device-motorola-peregrine/APKBUILD
  aports/device/device-motorola-peregrine/deviceinfo
  aports/device/linux-motorola-peregrine/00_fix_return_address.patch
  aports/device/linux-motorola-peregrine/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-motorola-peregrine/03_mdss_fb_refresh_rate.patch
  aports/device/linux-motorola-peregrine/APKBUILD
  aports/device/linux-motorola-peregrine/compiler-gcc6.h
  aports/device/linux-motorola-peregrine/config-motorola-peregrine.armhf
  aports/firmware/firmware-motorola-titan/APKBUILD
Labels: device

#1266 Include fbdebug tool in debug-shell hook
  aports/main/postmarketos-mkinitfs-hook-debug-shell/APKBUILD
  aports/main/postmarketos-mkinitfs/APKBUILD
  aports/main/postmarketos-mkinitfs/mkinitfs.sh
Labels: enhancement, initramfs

#1261 Add nonfree-firmware subpackage for fp2
  aports/device/device-fairphone-fp2/APKBUILD
Labels: device

#1268 Make nonfree depends optional (2/2): device pkgs
  aports/device/device-asus-flo/APKBUILD
  aports/device/device-htc-ace/APKBUILD
  aports/device/device-huawei-angler/APKBUILD
  aports/device/device-huawei-y530/APKBUILD
  aports/device/device-lenovo-karate/APKBUILD
  aports/device/device-lg-hammerhead/APKBUILD
  aports/device/device-motorola-peregrine/APKBUILD
  aports/device/device-motorola-titan/APKBUILD
  aports/device/device-nokia-n9/APKBUILD
  aports/device/device-nokia-n900/APKBUILD
  aports/device/device-oneplus-bacon/APKBUILD
  aports/device/device-oneplus-onyx/APKBUILD
  aports/device/device-samsung-espresso10/APKBUILD
  aports/device/device-samsung-i747m/APKBUILD
  aports/device/device-samsung-i9070/APKBUILD
  aports/device/device-samsung-i9100/APKBUILD
  aports/device/device-samsung-i9305/APKBUILD
  aports/device/device-samsung-i9505/APKBUILD
  aports/device/device-samsung-maguro/APKBUILD
  aports/device/device-semc-anzu/APKBUILD
  aports/device/device-sony-amami/APKBUILD
  aports/device/device-sony-castor-windy/APKBUILD
  aports/device/device-sony-honami/APKBUILD
  aports/device/device-t2m-flame/APKBUILD
  aports/device/device-teclast-x80pro/APKBUILD
  aports/device/device-xiaomi-armani/APKBUILD
  test/test_aports.py
Labels: enhancement, packaging

#1267 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1269 postmarketos-mkinitfs: don't fail without deviceinfo [skip ci]
  aports/main/postmarketos-mkinitfs/APKBUILD
  aports/main/postmarketos-mkinitfs/mkinitfs.sh
Labels: fix, packaging

#1270 Package the Plasma phone dialler
  aports/kde/plasma-phone-components/APKBUILD
  aports/kde/plasma-phone-components/unset-telepathy-dep.patch
  aports/main/telepathy-farstream/APKBUILD
  aports/main/telepathy-glib/APKBUILD
  aports/main/telepathy-qt5/APKBUILD
Labels: packaging, plasma-mobile

#1271 Use default partitions in odin export if not specified in deviceinfo
  pmb/export/odin.py
Labels: enhancement, pmbootstrap
