Repository postmarketOS/pmbootstrap, pull requests merged in 2018-06, with the labels that each got.

#1529 pmb/flasher: Fix regression with exporting odin images
  pmb/flasher/init.py
Labels: fix, pmbootstrap

#1532 kde/falkon: disable checks
  aports/kde/falkon/APKBUILD
Labels: infrastructure

#1533 Install dependencies of package checks
  pmb/build/_package.py
  pmb/config/__init__.py
  test/test_build_package.py
Labels: fix, pmbootstrap

#1535 Set Asus Grouper fastboot max size to 650
  aports/device/device-asus-grouper/APKBUILD
  aports/device/device-asus-grouper/deviceinfo
Labels: device, enhancement, packaging

#1548 Allow DEVTMPFS_MOUNT in kernel config
  pmb/config/__init__.py
Labels: fix, pmbootstrap

#1553 linux-amazon-thor: Modernize APKBUILD
  aports/device/linux-amazon-thor/00_fix_qaudio.patch
  aports/device/linux-amazon-thor/00_fix_smd_private.patch
  aports/device/linux-amazon-thor/03_msm_fix_trace.patch
  aports/device/linux-amazon-thor/APKBUILD
Labels: refactor

#1552 Adds asus-z00t device.
  aports/device/device-asus-z00t/90-touchscreen.rules
  aports/device/device-asus-z00t/APKBUILD
  aports/device/device-asus-z00t/deviceinfo
  aports/device/linux-asus-z00t/01_fix_gcc6_errors.patch
  aports/device/linux-asus-z00t/02_mdss_fb_refresh_rate.patch
  aports/device/linux-asus-z00t/05_dtb-fix.patch
  aports/device/linux-asus-z00t/APKBUILD
  aports/device/linux-asus-z00t/compiler-gcc6.h
  aports/device/linux-asus-z00t/config-asus-z00t.aarch64
  aports/firmware/firmware-asus-z00t/APKBUILD
Labels: device

#1555 Update Plasma to 5.13.0
  aports/kde/breeze/APKBUILD
  aports/kde/kactivitymanagerd/APKBUILD
  aports/kde/kdecoration/APKBUILD
  aports/kde/kscreen/APKBUILD
  aports/kde/kscreenlocker/APKBUILD
  aports/kde/ksysguard/APKBUILD
  aports/kde/kwayland-integration/APKBUILD
  aports/kde/kwin/0001-fbdev-support-RGB32-framebuffer-with-BGR-order.patch
  aports/kde/kwin/APKBUILD
  aports/kde/libkscreen/APKBUILD
  aports/kde/libksysguard/APKBUILD
  aports/kde/milou/APKBUILD
  aports/kde/plasma-nm/APKBUILD
  aports/kde/plasma-pa/APKBUILD
  aports/kde/plasma-phone-components/APKBUILD
  aports/kde/plasma-workspace/APKBUILD
  aports/kde/polkit-kde-agent/APKBUILD
  aports/kde/powerdevil/APKBUILD
Labels: ci-malfunction, update

#1556 aportgen linux: always override KBUILD_OUTPUT
  pmb/aportgen/linux.py
Labels: enhancement, pmbootstrap

#1564 Fix filename
  helpers/pmbootstrap-autocompletion.zsh
Labels: documentation, fix

#1565 device-samsung-p4wifi: Change touchscreen to /dev/input/event1
  aports/device/device-samsung-p4wifi/APKBUILD
  aports/device/device-samsung-p4wifi/deviceinfo
Labels: device, fix

#1572 device-samsung-manta: Enable touchscreen input
  aports/device/device-samsung-manta/APKBUILD
  aports/device/device-samsung-manta/deviceinfo
Labels: device, enhancement

#1573 pmbootstrap kconfig edit: support $builddir and $srcdir/build
  pmb/aportgen/linux.py
  pmb/build/menuconfig.py
Labels: fix, pmbootstrap, regression

#1580 Don't run dhcpcd on the raspberry pi
  aports/device/device-raspberry-pi/APKBUILD
  aports/device/device-raspberry-pi/deviceinfo
  aports/main/postmarketos-mkinitfs/APKBUILD
  aports/main/postmarketos-mkinitfs/init_functions.sh
Labels: device, fix, initramfs

#1395 osk-sdl: Update to 0.52
  aports/main/osk-sdl/APKBUILD
Labels: update

#1597 temp/raspberrypi-bootloader: remove (to use Alpine's package again)
  aports/temp/raspberrypi-bootloader/APKBUILD
Labels: packaging

#1583 device-raspberry-pi: use linux-firmware-brcm
  aports/device/bluetooth-raspberry-pi/50-bluetooth-hci-auto-poweron.rules
  aports/device/bluetooth-raspberry-pi/APKBUILD
  aports/device/bluetooth-raspberry-pi/bluetooth-raspberry-pi.post-install
  aports/device/bluetooth-raspberry-pi/pi-bluetooth.openrc
  aports/device/device-raspberry-pi/APKBUILD
  aports/firmware/firmware-pi-bluetooth/APKBUILD
  aports/temp/linux-firmware/APKBUILD
Labels: device, fix, packaging

#1600 device/device-raspberry-pi3: new aports
  aports/device/device-raspberry-pi3/95-vchiq-permissions.rules
  aports/device/device-raspberry-pi3/APKBUILD
  aports/device/device-raspberry-pi3/cmdline.txt
  aports/device/device-raspberry-pi3/config.txt
  aports/device/device-raspberry-pi3/device-raspberry-pi3-kernel-rpi.post-install
  aports/device/device-raspberry-pi3/deviceinfo
  aports/device/device-raspberry-pi3/usercfg.txt
  aports/device/device-raspberry-pi3/weston.ini
Labels: ci-malfunction
