Repository postmarketOS/pmbootstrap, pull requests merged in 2018-04, with the labels that each got.

#1382 Update apk-file to version 0.3.0 and new repository
  aports/main/apk-file/APKBUILD
Labels: packaging, update

#1386 Update linux-samsung-p4wifi to kernel 4.16
  aports/device/device-samsung-p4wifi/APKBUILD
  aports/device/device-samsung-p4wifi/deviceinfo
  aports/device/linux-samsung-p4wifi/APKBUILD
  aports/device/linux-samsung-p4wifi/config-samsung-p4wifi.armhf
Labels: device, kernel, update

#1309 Add initial packages for flounder port
  aports/device/device-htc-flounder/APKBUILD
  aports/device/device-htc-flounder/deviceinfo
  aports/device/linux-htc-flounder/APKBUILD
  aports/device/linux-htc-flounder/compiler-gcc6.h
  aports/device/linux-htc-flounder/config-htc-flounder.aarch64
  aports/firmware/firmware-htc-flounder/APKBUILD
Labels: device, dont_merge_pr, help wanted

#1393 flasher: install depends of the method specified in the arguments
  pmb/flasher/init.py
Labels: fix, pmbootstrap

#1399 update oneplus2 kernel
  aports/device/linux-oneplus-oneplus2/APKBUILD
  aports/device/linux-oneplus-oneplus2/config-oneplus-oneplus2.aarch64
Labels: device, kernel, update

#1390 Add some aliases.
  helpers/envsetup.sh
  test/static_code_analysis.sh
Labels: enhancement

#1394 Ask to copy SSH public keys during init
  pmb/config/__init__.py
  pmb/config/init.py
  pmb/install/_install.py
Labels: enhancement, pmbootstrap, usability

#1400 Bump pkgrel due to libressl soname upgrade
  aports/kde/qca-qt5/APKBUILD
  aports/main/qt5-qtbase/APKBUILD
  aports/modem/libsamsung-ipc/APKBUILD
Labels: dont_merge_pr

#1392 Initial Work for HTC One M8 Port
  aports/device/device-htc-m8/90-android-touch-dev.rules
  aports/device/device-htc-m8/APKBUILD
  aports/device/device-htc-m8/deviceinfo
  aports/device/device-htc-m8/initfs-hook.sh
  aports/device/linux-htc-m8/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-htc-m8/APKBUILD
  aports/device/linux-htc-m8/compiler-gcc6.h
  aports/device/linux-htc-m8/config-htc-m8.armhf
  aports/device/linux-htc-m8/psmouse_base.patch
Labels: device

#1402 Package libhybris
  aports/hybris/android-headers-4.4/APKBUILD
  aports/hybris/android-headers-4.4/android-headers.pc
  aports/hybris/android-headers-7.1/APKBUILD
  aports/hybris/libhybris/0001-Make-libhybris-compile-with-musl.patch
  aports/hybris/libhybris/0002-tests-Regression-test-for-EGL-glibc-TLS-conflict.patch
  aports/hybris/libhybris/0003-Implement-X11-EGL-platform-based-on-wayland-code.patch
  aports/hybris/libhybris/APKBUILD
Labels: packaging

#1409 initfs hook_ls: make clear what's not installed
  pmb/chroot/initfs_hooks.py
Labels: pmbootstrap, usability

#1389 Add initial device support for Sony Xperia T3 (sony-seagull)
  aports/device/device-sony-seagull/APKBUILD
  aports/device/device-sony-seagull/deviceinfo
  aports/device/linux-sony-seagull/01_fix_return_address.patch
  aports/device/linux-sony-seagull/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-sony-seagull/03_fix_various_include_directives.patch
  aports/device/linux-sony-seagull/04_timeconst_fix.patch
  aports/device/linux-sony-seagull/05_psmouse_base.patch
  aports/device/linux-sony-seagull/APKBUILD
  aports/device/linux-sony-seagull/compiler-gcc6.h
  aports/device/linux-sony-seagull/config-sony-seagull.armhf
Labels: device

#1412 Initial support for motorola-athene
  aports/device/device-motorola-athene/APKBUILD
  aports/device/device-motorola-athene/deviceinfo
  aports/device/linux-motorola-athene/01_fix_gcc6_errors.patch
  aports/device/linux-motorola-athene/APKBUILD
  aports/device/linux-motorola-athene/compiler-gcc6.h
  aports/device/linux-motorola-athene/config-motorola-athene.aarch64
Labels: device

#1388 "pkgrel_bump --auto": Handle subpackages properly
  pmb/helpers/pkgrel_bump.py
  test/test_pkgrel_bump.py
  test/testdata/pkgrel_bump/aports/testsubpkg/APKBUILD
  test/testdata/pkgrel_bump/aports/testsubpkg/testapp.c
Labels: fix, pmbootstrap

#1420 Support matchbox
  aports/main/postmarketos-ui-matchbox/APKBUILD
  aports/main/postmarketos-ui-matchbox/postmarketos-ui-matchbox.post-install
  aports/main/postmarketos-ui-matchbox/start_matchbox.sh
  aports/matchbox/libmatchbox/APKBUILD
  aports/matchbox/libxsettings-client/01-ignore-xsettings-common-h.patch
  aports/matchbox/libxsettings-client/APKBUILD
  aports/matchbox/libxsettings/APKBUILD
  aports/matchbox/matchbox-common/APKBUILD
  aports/matchbox/matchbox-desktop/01-needed-libraries.patch
  aports/matchbox/matchbox-desktop/APKBUILD
  aports/matchbox/matchbox-keyboard/APKBUILD
  aports/matchbox/matchbox-panel-manager/01-linking-fix.patch
  aports/matchbox/matchbox-panel-manager/APKBUILD
  aports/matchbox/matchbox-panel/APKBUILD
  aports/matchbox/matchbox-window-manager/01-build-themes.patch
  aports/matchbox/matchbox-window-manager/02-config.patch
  aports/matchbox/matchbox-window-manager/03-default-theme.patch
  aports/matchbox/matchbox-window-manager/04-install-themes.patch
  aports/matchbox/matchbox-window-manager/05-makefile.patch
  aports/matchbox/matchbox-window-manager/06-tidy-help-text.patch
  aports/matchbox/matchbox-window-manager/APKBUILD
  aports/matchbox/mb-applet-input-manager/APKBUILD
Labels: packaging

#1424 Add envkernel.sh: instant mainlining environment
  helpers/envkernel.fish
  helpers/envkernel.sh
  pmb/helpers/frontend.py
  pmb/parse/arguments.py
  test/static_code_analysis.sh
Labels: enhancement, kernel, usability

#1428 Device samsung i8190 (Galaxy SIII mini)
  aports/device/device-samsung-i8190/APKBUILD
  aports/device/device-samsung-i8190/deviceinfo
  aports/device/device-samsung-i8190/init-usb-hook.sh
  aports/device/linux-samsung-i8190/00_fix_makefile.patch
  aports/device/linux-samsung-i8190/01_fix_return_address.patch
  aports/device/linux-samsung-i8190/02_timeconst_fix.patch
  aports/device/linux-samsung-i8190/03_fix_rndis.patch
  aports/device/linux-samsung-i8190/APKBUILD
  aports/device/linux-samsung-i8190/compiler-gcc6.h
  aports/device/linux-samsung-i8190/config-samsung-i8190.armhf
Labels: device

#1437 Initial support for Motorola Moto G4 Play (motorola-harpia)
  aports/device/device-motorola-harpia/APKBUILD
  aports/device/device-motorola-harpia/deviceinfo
  aports/device/device-motorola-harpia/initfs-hook.sh
  aports/device/linux-motorola-harpia/APKBUILD
  aports/device/linux-motorola-harpia/compiler-gcc6.h
  aports/device/linux-motorola-harpia/config-motorola-harpia.armhf
Labels: device

#1324 i9195/WiFi support
  aports/device/device-samsung-i9195/APKBUILD
  aports/firmware/firmware-samsung-i9195/APKBUILD
Labels: device, enhancement

#1410 Display wiki link on dependency error
  pmb/parse/depends.py
  test/test_parse_depends.py
Labels: pmbootstrap, usability

#1432 Set all of user's groups in "pmbootstrap install"
  aports/main/postmarketos-base/APKBUILD
  aports/main/postmarketos-base/postmarketos-base.post-install
  pmb/config/__init__.py
  pmb/install/_install.py
Labels: fix, packaging, pmbootstrap

#1439 Fix issues with lock.sh for i3wm/N900
  aports/main/postmarketos-ui-i3wm/APKBUILD
  aports/main/postmarketos-ui-i3wm/lock.sh
Labels: device, fix, packaging

#1446 Fix randomized pkg providers for python < 3.6
  pmb/parse/apkindex.py
Labels: fix, pmbootstrap

#1449 Fix binfmt_misc check
  pmb/helpers/other.py
Labels: fix, pmbootstrap
