Repository postmarketOS/pmbootstrap, pull requests merged in 2018-05, with the labels that each got.

#1442 Add install flag to generate separate boot and system images
  pmb/export/frontend.py
  pmb/export/symlinks.py
  pmb/install/_install.py
  pmb/install/blockdevice.py
  pmb/parse/arguments.py
Labels: enhancement, pmbootstrap

#1452 [ui-mate] Set postmarketOS artwork as default wallpaper
  aports/main/postmarketos-ui-mate/000-system-background.gschema.override
  aports/main/postmarketos-ui-mate/APKBUILD
  aports/main/postmarketos-ui-mate/postmarketos-ui-mate.post-install
Labels: enhancement, packaging

#1466 [ui-weston] Set postmarketos artwork as default wallpaper
  aports/device/device-asus-flo/APKBUILD
  aports/device/device-asus-flo/weston.ini
  aports/device/device-lg-hammerhead/APKBUILD
  aports/device/device-lg-hammerhead/weston.ini
  aports/device/device-lg-mako/APKBUILD
  aports/device/device-lg-mako/weston.ini
  aports/device/device-motorola-titan/APKBUILD
  aports/device/device-motorola-titan/weston.ini
  aports/device/device-nokia-n9/APKBUILD
  aports/device/device-nokia-n9/weston.ini
  aports/device/device-nokia-n900/APKBUILD
  aports/device/device-nokia-n900/weston.ini
  aports/device/device-oneplus-bacon/APKBUILD
  aports/device/device-oneplus-bacon/weston.ini
  aports/device/device-qemu-aarch64/APKBUILD
  aports/device/device-qemu-aarch64/weston.ini
  aports/device/device-qemu-amd64/APKBUILD
  aports/device/device-qemu-amd64/weston.ini
  aports/device/device-sony-sirius/APKBUILD
  aports/device/device-sony-sirius/weston.ini
  aports/main/postmarketos-ui-weston/APKBUILD
  aports/main/postmarketos-ui-weston/weston.ini.default
Labels: enhancement, packaging

#1440 Samsung-i8190 wifi now working
  aports/device/device-samsung-i8190/APKBUILD
  aports/device/device-samsung-i8190/module-config.conf
  aports/device/device-samsung-i8190/modules-load.conf
  aports/device/linux-samsung-i8190/04_fix_bcma.patch
  aports/device/linux-samsung-i8190/05_change_dhd_firmware_path.patch
  aports/device/linux-samsung-i8190/APKBUILD
  aports/device/linux-samsung-i8190/config-samsung-i8190.armhf
  aports/firmware/firmware-samsung-i8190/APKBUILD
Labels: device

#1469 Add info about --method to error message
  pmb/flasher/run.py
Labels: enhancement, pmbootstrap

#1471 Package the grass wallpapers
  aports/main/postmarketos-artwork-wallpapers/APKBUILD
Labels: packaging, update

#1462 linux-postmarketos-qcom: Remove composite usb gadget for networking
  aports/main/linux-postmarketos-qcom/APKBUILD
  aports/main/linux-postmarketos-qcom/config-postmarketos-qcom.armhf
Labels: fix, kernel

#1474 Install the "device-aaa-bbb-kernel-XXX" package instead of the "linux-postmarketos-XXX" to also install the related depends
  pmb/install/_install.py
Labels: fix, pmbootstrap

#1480 weston: Add wayland-dev make dependency, add patch for compilation with freerdp 2.0.0-rc2
  aports/main/weston/0007-Fix-compositor-rdp-compilation-with-freerdp-2.0.0-rc.patch
  aports/main/weston/APKBUILD
Labels: fix

#1381 ofono QMI: mainline kernel support
  aports/device/device-samsung-i9195/APKBUILD
  aports/modem/modem-qcom-msm-downstream-common/APKBUILD
  aports/modem/modem-qcom-msm-downstream-common/udev.rules
  aports/modem/modem-qcom-msm-mainline-common/APKBUILD
  aports/modem/modem-qcom-msm-mainline-common/udev.rules
  aports/modem/ofono/APKBUILD
  aports/modem/ofono/support-smdpkt.patch
  aports/modem/ofono/udev.rules
  aports/modem/qcom_rmtfs/APKBUILD
  aports/modem/qcom_rmtfs/udev.rules
  aports/modem/qcom_rmtfs/update-storage-paths.patch
  aports/modem/rpmsgexport/APKBUILD
Labels: dont_merge_pr, enhancement, packaging

#1484 Add support for the Samsung Galaxy Tab 3 7.0 (lt023g)
  aports/device/device-samsung-lt023g/APKBUILD
  aports/device/device-samsung-lt023g/deviceinfo
  aports/device/linux-samsung-lt023g/418df63adac56841ef6b0f1fcf435bc64d4ed177.patch
  aports/device/linux-samsung-lt023g/455bd4c430b0c0a361f38e8658a0d6cb469942b5.patch
  aports/device/linux-samsung-lt023g/APKBUILD
  aports/device/linux-samsung-lt023g/compiler-gcc6.h
  aports/device/linux-samsung-lt023g/config-samsung-lt023g.armhf
  aports/device/linux-samsung-lt023g/timeconst_fix.patch
Labels: device

#1486 Update Nokia N9 to kernel v4.17-rc4
  aports/device/device-nokia-n9/APKBUILD
  aports/device/linux-nokia-n9/0001-SREv2.patch
  aports/device/linux-nokia-n9/0002-drm-add-rename-MIPI_DCS_SET_PARTIAL_XXX.patch
  aports/device/linux-nokia-n9/0003-drm-omap-panel-dsi-cm-use-defines-from-mipi_display..patch
  aports/device/linux-nokia-n9/0004-ARM-dts-n9-add-display-support.patch
  aports/device/linux-nokia-n9/0005-Revert-drm-omap-work-around-for-omap3-display-enable.patch
  aports/device/linux-nokia-n9/0006-HACK-drm-omap-panel-dsi-cm-force-0xff-for-brigthness.patch
  aports/device/linux-nokia-n9/0007-ARM-dts-N9-N950-Add-touchscreen-support.patch
  aports/device/linux-nokia-n9/0008-misc-apds990x-Add-device-tree-support.patch
  aports/device/linux-nokia-n9/0009-misc-apds990x-convert-to-iio.patch
  aports/device/linux-nokia-n9/0010-ARM-dts-N9-Add-support-for-apds990x-ALS-PS.patch
  aports/device/linux-nokia-n9/0011-HACK-export-dma-access-functions-needed-by-PVR-drive.patch
  aports/device/linux-nokia-n9/APKBUILD
Labels: device, kernel, update

#1481 Update Plasma to 5.12.5
  aports/kde/breeze/APKBUILD
  aports/kde/kactivitymanagerd/APKBUILD
  aports/kde/kdecoration/APKBUILD
  aports/kde/kscreen/APKBUILD
  aports/kde/kscreenlocker/APKBUILD
  aports/kde/ksysguard/APKBUILD
  aports/kde/kwayland-integration/APKBUILD
  aports/kde/kwin/APKBUILD
  aports/kde/libkscreen/APKBUILD
  aports/kde/libksysguard/APKBUILD
  aports/kde/milou/APKBUILD
  aports/kde/plasma-nm/APKBUILD
  aports/kde/plasma-pa/APKBUILD
  aports/kde/plasma-workspace/APKBUILD
  aports/kde/polkit-kde-agent/APKBUILD
  aports/kde/powerdevil/APKBUILD
Labels: ci-malfunction, update

#1468 gcc-*: fix compiling in strict mode [skip ci]
  aports/cross/gcc-aarch64/APKBUILD
  aports/cross/gcc-armhf/APKBUILD
  aports/cross/gcc-x86_64/APKBUILD
  pmb/aportgen/core.py
  pmb/aportgen/gcc.py
Labels: ci-malfunction, fix, packaging, pmbootstrap

#1497 kde/konsole Add missing build dependency
  aports/kde/konsole/APKBUILD
Labels: fix, packaging

#1470 I3tweaks
  aports/device/device-nokia-n900/APKBUILD
  aports/device/device-nokia-n900/i3wm/bq27200_status.sh
  aports/device/device-nokia-n900/i3wm/i3status.conf
  aports/device/device-nokia-n900/i3wm/i3wm.conf
Labels: device, enhancement, packaging

#1515 Update linux-samsung-p4wifi config to be based on mainline tegra_defconfig
  aports/device/linux-samsung-p4wifi/APKBUILD
  aports/device/linux-samsung-p4wifi/config-samsung-p4wifi.armhf
Labels: device, kernel, update

#1445 Only use gtk+2.0-maemo for Hildon
  aports/main/postmarketos-ui-hildon/APKBUILD
  aports/main/postmarketos-ui-matchbox/APKBUILD
  aports/main/postmarketos-ui-mate/APKBUILD
  aports/main/postmarketos-ui-xfce4/APKBUILD
Labels: fix, packaging
