Repository postmarketOS/pmbootstrap, pull requests merged in 2018-03, with the labels that each got.

#1277 Always prefer native/device arch when building
  pmb/build/autodetect.py
Labels: fix, pmbootstrap, usability

#1280 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1040 Add NetworkManager and PulseAudio applets to Plasma
  aports/kde/modemmanager-qt/APKBUILD
  aports/kde/networkmanager-qt/APKBUILD
  aports/kde/plasma-nm/APKBUILD
  aports/kde/plasma-pa/APKBUILD
  aports/kde/plasma-phone-components/APKBUILD
  aports/kde/qca-qt5/APKBUILD
  aports/main/postmarketos-ui-plasma-mobile/APKBUILD
Labels: packaging, plasma-mobile

#1281 Fix Nokia N9 build and update kernel
  aports/device/device-nokia-n9/APKBUILD
  aports/device/device-nokia-n9/deviceinfo
  aports/device/linux-nokia-n9/0001-SEB.patch
  aports/device/linux-nokia-n9/0001-SREv2.patch
  aports/device/linux-nokia-n9/0002-drm-add-rename-MIPI_DCS_SET_PARTIAL_XXX.patch
  aports/device/linux-nokia-n9/0003-drm-omap-panel-dsi-cm-use-defines-from-mipi_display..patch
  aports/device/linux-nokia-n9/0004-ARM-dts-n9-add-display-support.patch
  aports/device/linux-nokia-n9/0005-Revert-drm-omap-work-around-for-omap3-display-enable.patch
  aports/device/linux-nokia-n9/0006-HACK-drm-omap-panel-dsi-cm-force-0xff-for-brigthness.patch
  aports/device/linux-nokia-n9/0007-ARM-dts-N9-Add-support-for-volume-keys.patch
  aports/device/linux-nokia-n9/0007-ARM-dts-N9-N950-Add-touchscreen-support.patch
  aports/device/linux-nokia-n9/0008-misc-apds990x-Add-device-tree-support.patch
  aports/device/linux-nokia-n9/0009-misc-apds990x-convert-to-iio.patch
  aports/device/linux-nokia-n9/0010-ARM-dts-N9-Add-support-for-apds990x-ALS-PS.patch
  aports/device/linux-nokia-n9/0011-HACK-export-dma-access-functions-needed-by-PVR-drive.patch
  aports/device/linux-nokia-n9/APKBUILD
Labels: device, update

#388 NetworkManager support
  aports/main/postmarketos-base/APKBUILD
  aports/main/postmarketos-base/networkmanager.conf
  aports/main/postmarketos-base/postmarketos-base.post-install
Labels: packaging, usability

#1283 linux-postmarketos-mainline: fix weston (x86_64)
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-mainline/config-postmarketos-mainline.x86_64
Labels: fix, kernel

#1201 Only download APKINDEX for relevant architectures
  pmb/build/_package.py
  pmb/chroot/apk.py
  pmb/chroot/apk_static.py
  pmb/chroot/init.py
  pmb/helpers/frontend.py
  pmb/helpers/repo.py
  pmb/parse/arguments.py
  test/test_upstream_compatibility.py
Labels: enhancement, pmbootstrap

#1290 Fix updating packages in chroots
  pmb/chroot/apk.py
Labels: fix, pmbootstrap

#1279 New device: Samsung Galaxy Tab 10.1 (p4wifi)
  aports/device/device-samsung-p4wifi/APKBUILD
  aports/device/device-samsung-p4wifi/deviceinfo
  aports/device/linux-samsung-p4wifi/APKBUILD
  aports/device/linux-samsung-p4wifi/compiler-gcc6.h
  aports/device/linux-samsung-p4wifi/config-samsung-p4wifi.armhf
  aports/firmware/firmware-samsung-p4wifi/APKBUILD
Labels: device

#1282 Fix build --src for foreign-arch chroots
  pmb/build/_package.py
  test/test_build_package.py
Labels: fix, pmbootstrap

#1293 Remove /etc/network/interfaces and networking service from device packages
  aports/device/device-lenovo-karate/APKBUILD
  aports/device/device-lenovo-karate/device-lenovo-karate.post-install
  aports/device/device-nokia-n900/APKBUILD
  aports/device/device-nokia-n900/device-nokia-n900.post-install
  aports/device/device-qemu-aarch64/APKBUILD
  aports/device/device-qemu-aarch64/interfaces
  aports/device/device-qemu-amd64/APKBUILD
  aports/device/device-qemu-amd64/interfaces
  aports/device/device-qemu-vexpress/APKBUILD
  aports/device/device-qemu-vexpress/interfaces
  aports/device/device-sony-castor-windy/device-sony-castor_windy.post-install
  aports/main/postmarketos-base/APKBUILD
  aports/main/postmarketos-base/postmarketos-base.post-install
Labels: packaging, refactor

#1285 Implement charging mode
  aports/main/charging-sdl/APKBUILD
  aports/main/postmarketos-mkinitfs/APKBUILD
  aports/main/postmarketos-mkinitfs/init.sh.in
  aports/main/postmarketos-mkinitfs/init_functions.sh
  aports/main/postmarketos-mkinitfs/mkinitfs.sh
Labels: dont_merge_pr, enhancement, initramfs

#1295 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
Labels: kernel, update

#1296 Depend on libepoxy-dev from kdeclarative
  aports/kde/kdeclarative/APKBUILD
Labels: packaging, plasma-mobile

#1297 Update Plasma to 5.12.3
  aports/kde/breeze/APKBUILD
  aports/kde/kactivitymanagerd/APKBUILD
  aports/kde/kdecoration/APKBUILD
  aports/kde/kscreen/APKBUILD
  aports/kde/kscreenlocker/APKBUILD
  aports/kde/ksysguard/APKBUILD
  aports/kde/kwin/APKBUILD
  aports/kde/libkscreen/APKBUILD
  aports/kde/libksysguard/APKBUILD
  aports/kde/milou/APKBUILD
  aports/kde/plasma-nm/APKBUILD
  aports/kde/plasma-pa/APKBUILD
  aports/kde/plasma-settings/APKBUILD
  aports/kde/plasma-workspace/APKBUILD
  aports/kde/polkit-kde-agent/APKBUILD
  aports/kde/powerdevil/APKBUILD
Labels: packaging, plasma-mobile

#1303 Fix building packages by provides name
  pmb/build/other.py
  pmb/config/__init__.py
  pmb/parse/bootimg.py
Labels: fix, pmbootstrap

#1306 pmbootstrap zap -m: delete outdated packages too
  pmb/chroot/zap.py
  pmb/helpers/frontend.py
  pmb/parse/apkindex.py
  pmb/parse/arguments.py
Labels: enhancement, pmbootstrap, refactor

#1278 Skip virtual packages when parsing APKINDEX
  pmb/parse/apkindex.py
  test/test_parse_apkindex.py
  test/testdata/apkindex/virtual_package
Labels: fix, pmbootstrap

#1311 Add ZTE Kis3 / ZTE Open C
  aports/device/device-zte-kis3/APKBUILD
  aports/device/device-zte-kis3/deviceinfo
  aports/device/linux-zte-kis3/00_fix_return_address.patch
  aports/device/linux-zte-kis3/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-zte-kis3/APKBUILD
  aports/device/linux-zte-kis3/compiler-gcc6.h
  aports/device/linux-zte-kis3/config-zte-kis3.armhf
Labels: device

#1313 i9195: add touchscreen to deviceinfo
  aports/device/device-samsung-i9195/APKBUILD
  aports/device/device-samsung-i9195/deviceinfo
Labels: device, enhancement

#1317 Mount tmpfs in chroot's /dev folders
  pmb/chroot/init.py
  pmb/chroot/mount.py
Labels: enhancement, pmbootstrap

#1312 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1318 peregrine: framebuffer patch and xorg config
  aports/device/device-motorola-peregrine/APKBUILD
  aports/device/device-motorola-peregrine/xorg.conf
  aports/device/linux-motorola-peregrine/06_fix_mdss_fb_rgb_mode.patch
  aports/device/linux-motorola-peregrine/APKBUILD
Labels: device, enhancement

#1316 Properly escape commands in pmb.chroot.user()
  pmb/aportgen/device.py
  pmb/build/_package.py
  pmb/build/menuconfig.py
  pmb/build/other.py
  pmb/chroot/distccd.py
  pmb/chroot/root.py
  pmb/chroot/user.py
  pmb/helpers/run.py
  test/test_build_package.py
  test/test_shell_escape.py
Labels: fix, pmbootstrap

#1314 i9195/Qualcomm modem support
  aports/device/device-samsung-i9195/APKBUILD
  aports/device/linux-samsung-i9195/APKBUILD
  aports/firmware/firmware-samsung-i9195/APKBUILD
  aports/modem/libqipcrtr4msmipc/APKBUILD
  aports/modem/libsamsung-ipc/0001-i9100-modem-firmware-device-path.patch
  aports/modem/libsamsung-ipc/APKBUILD
  aports/modem/libsmdpkt_wrapper/APKBUILD
  aports/modem/msmipc-dev/APKBUILD
  aports/modem/ofono/APKBUILD
  aports/modem/ofono/ofono.initd
  aports/modem/ofono/support-smdpkt.patch
  aports/modem/qcom_rmtfs/APKBUILD
  aports/modem/qcom_rmtfs/point-storage-to-paths-in-etc.patch
  aports/modem/qcom_rmtfs/qcom_rmtfs.initd
  aports/modem/qcom_rmtfs/qcom_rmtfs.post-install
  aports/modem/qcom_rmtfs/support-uio.patch
  aports/modem/qrtr/APKBUILD
  aports/modem/qrtr/fix-cfg-include.patch
Labels: device, enhancement

#1326 [xfce4] Add default icon theme, set pmOS wallpaper and add battery icon in top panel
  aports/main/postmarketos-ui-xfce4/APKBUILD
Labels: packaging, update

#1328 samsung-p4wifi: Load wifi modules, add audio output, remove touch screen calibration
  aports/device/device-samsung-p4wifi/90-device-samsung-p4wifi-audio.rules
  aports/device/device-samsung-p4wifi/90-device-samsung-p4wifi-jack.rules
  aports/device/device-samsung-p4wifi/APKBUILD
  aports/device/device-samsung-p4wifi/HiFi
  aports/device/device-samsung-p4wifi/deviceinfo
  aports/device/device-samsung-p4wifi/modprobe.conf
  aports/device/device-samsung-p4wifi/modules-load.conf
  aports/device/device-samsung-p4wifi/wm8994aif1.conf
  aports/device/linux-samsung-p4wifi/APKBUILD
  aports/device/linux-samsung-p4wifi/config-samsung-p4wifi.armhf
Labels: device, enhancement

#1331 Travis CI: folded output/default tracebacks
  .travis.yml
  .travis/common.sh
  .travis/travis_after_failure.sh
  .travis/travis_script.sh
  test/testcases_fast.sh
Labels: enhancement, infrastructure, usability

#1334 linux-xiaomi-armani: disable kgsl 3d driver
  aports/device/linux-xiaomi-armani/APKBUILD
  aports/device/linux-xiaomi-armani/config-xiaomi-armani.armhf
Labels: device, fix

#1330 Qemu test case: wait dynamically until booted
  test/test_qemu_running_processes.py
Labels: enhancement, infrastructure, pmbootstrap

#1338 Add kwayland-integration to plasma-mobile dep
  aports/kde/kwayland-integration/APKBUILD
  aports/main/postmarketos-ui-plasma-mobile/APKBUILD
Labels: packaging, plasma-mobile

#1320 pmbootstrap newapkbuild: Properly parse arguments
  pmb/build/newapkbuild.py
  pmb/config/__init__.py
  pmb/helpers/frontend.py
  pmb/parse/arguments.py
Labels: fix, pmbootstrap

#1337 recovery-installer: include tar inside recovery.zip
  aports/main/postmarketos-android-recovery-installer/APKBUILD
  aports/main/postmarketos-android-recovery-installer/build_zip.sh
Labels: android-recovery-zip, fix

#1341 Export some environment variables when starting plasma
  aports/main/postmarketos-ui-plasma-mobile/APKBUILD
  aports/main/postmarketos-ui-plasma-mobile/start_plasma.sh
Labels: enhancement, packaging

#1039 Motorola Droid 4 (maserati)
  aports/device/device-motorola-maserati/10-safestrap-maserati.sh
  aports/device/device-motorola-maserati/APKBUILD
  aports/device/device-motorola-maserati/deviceinfo
  aports/device/linux-motorola-maserati/01_maserati-fix-gcc6-compile.patch
  aports/device/linux-motorola-maserati/APKBUILD
  aports/device/linux-motorola-maserati/compiler-gcc6.h
  aports/device/linux-motorola-maserati/config-motorola-maserati.armhf
Labels: device

#1339 Fix regex in recovery installer
  aports/main/postmarketos-android-recovery-installer/APKBUILD
  aports/main/postmarketos-android-recovery-installer/pmos_install_functions
Labels: android-recovery-zip, fix

#1327 Set the hostname as the device name
  pmb/config/__init__.py
  pmb/config/init.py
  pmb/helpers/other.py
  pmb/install/_install.py
  test/test_questions.py
Labels: enhancement, pmbootstrap

#1346 New device: Xiaomi Redmi 4X (xiaomi-santoni)
  aports/device/device-xiaomi-santoni/APKBUILD
  aports/device/device-xiaomi-santoni/deviceinfo
  aports/device/linux-xiaomi-santoni/02_fix_msm_dba.patch
  aports/device/linux-xiaomi-santoni/03_fix_rndis_ipa_trace_header_not_found.patch
  aports/device/linux-xiaomi-santoni/APKBUILD
  aports/device/linux-xiaomi-santoni/compiler-gcc6.h
  aports/device/linux-xiaomi-santoni/config-xiaomi-santoni.aarch64
Labels: device

#1348 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1340 README: Update with lots of usage examples
  README.md
Labels: documentation, update

#1357 Kernel updates
  aports/main/linux-postmarketos-lts/APKBUILD
  aports/main/linux-postmarketos-mainline/APKBUILD
  aports/main/linux-postmarketos-stable/APKBUILD
Labels: kernel, update

#1355 Package resolving: Don't fail on fuzzy versions
  pmb/parse/apkindex.py
Labels: fix, pmbootstrap

#1359 Fix dependency resolver being stuck after reboot
  pmb/parse/apkindex.py
Labels: fix, pmbootstrap

#1358 Add additional files into initramfs when debug-shell is installed
  aports/main/postmarketos-mkinitfs-hook-debug-shell/20-debug-shell.files
  aports/main/postmarketos-mkinitfs-hook-debug-shell/APKBUILD
  aports/main/postmarketos-mkinitfs/APKBUILD
  aports/main/postmarketos-mkinitfs/TODO
  aports/main/postmarketos-mkinitfs/mkinitfs.sh
Labels: enhancement, initramfs

#1366 New device: oneplus oneplus2
  aports/device/device-oneplus-oneplus2/APKBUILD
  aports/device/device-oneplus-oneplus2/deviceinfo
  aports/device/device-oneplus-oneplus2/initfs-hook.sh
  aports/device/linux-oneplus-oneplus2/00_mt_width_major_params.patch
  aports/device/linux-oneplus-oneplus2/APKBUILD
  aports/device/linux-oneplus-oneplus2/compiler-gcc6.h
  aports/device/linux-oneplus-oneplus2/config-oneplus-oneplus2.aarch64
Labels: device

#1369 Travis: Check for device documentation
  .travis/travis_script.sh
  test/check_devices_in_wiki.py
Labels: documentation, enhancement, infrastructure

#1365 New device: hTC Incredible S (htc-vivo)
  aports/device/device-htc-vivo/APKBUILD
  aports/device/device-htc-vivo/deviceinfo
  aports/device/device-htc-vivo/initfs-hook.sh
  aports/device/linux-htc-vivo/02_gpu-msm-fix-gcc5-compile.patch
  aports/device/linux-htc-vivo/03_use-static-inline-in-ftrace.h.patch
  aports/device/linux-htc-vivo/04-fix-redefinition-of-unregister_con_driver.patch
  aports/device/linux-htc-vivo/APKBUILD
  aports/device/linux-htc-vivo/compiler-gcc6.h
  aports/device/linux-htc-vivo/config-htc-vivo.armhf
Labels: device

#1372 change log output order 'flash_system' before 'flash_kernel'
  pmb/install/_install.py
Labels: enhancement, pmbootstrap

#1373 "...flasher flash_rootfs" instead of "..._system"
  README.md
  helpers/pmbootstrap-autocompletion.zsh
  pmb/config/__init__.py
  pmb/export/symlinks.py
  pmb/flasher/frontend.py
  pmb/helpers/frontend.py
  pmb/install/_install.py
  pmb/parse/arguments.py
Labels: enhancement, pmbootstrap

#1377 re-enable rdp for weston
  aports/main/weston/APKBUILD
Labels: enhancement

#1378 New device: hTC Desire 816 (htc-a5ul)
  aports/device/device-htc-a5ul/APKBUILD
  aports/device/device-htc-a5ul/deviceinfo
  aports/device/device-htc-a5ul/initfs-hook.sh
  aports/device/linux-htc-a5ul/0003-Fix-CC-error.patch
  aports/device/linux-htc-a5ul/APKBUILD
  aports/device/linux-htc-a5ul/compiler-gcc6.h
  aports/device/linux-htc-a5ul/config-htc-a5ul.armhf
Labels: device

#1329 Fix: /var/cache/distfiles writable by everyone
  pmb/build/init.py
  pmb/config/__init__.py
  pmb/config/init.py
  pmb/helpers/other.py
Labels: fix, pmbootstrap
